config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  resources :dissertations, only: [:new, :create, :destroy]
  resources :users
  
  namespace :admin do
    resources :users, only: [:new, :create, :destroy]
  end
<<<<<<< HEAD
=======

>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b
  #Ogólna

  root 'static_pages#index'

  get 'welcome', to: 'static_pages#welcome', as: 'welcome'

  get 'index', to: 'static_pages#index', as: 'index'
  
  get 'authors', to: 'static_pages#authors', as: 'authors'

  get 'logowanie', to: 'static_pages#logowanie', as: 'logowanie'

  get 'help', to: 'static_pages#help', as: 'help'

  #Student

  get 'student', to: 'users#student', as: 'student'

  get 'materialy', to: 'users#materialy', as: 'materialy'

  get 'harmonogram', to: 'users#harmonogram', as: 'harmonogram'

  get 'instrukcja', to: 'users#instrukcja', as: 'instrukcja'

  get 'wyloguj', to: 'users#wyloguj', as: 'wyloguj'

  get 'praca', to: 'dissertations#new', as: 'praca'

  get 'pomoc', to: 'users#pomoc', as: 'pomoc'

<<<<<<< HEAD
  #Promoter

  get 'promoter', to: 'users#promoter', as: 'promoter'

  patch 'dissertations/:id', to: 'dissertations#edit', as: 'update_dissertation'
  
  get 'studenci', to: 'dissertations#studenci', as: 'studenci'

  get 'wylogowanie', to: 'users#wylogowanie', as: 'wylogowanie'

   #Admin

   get 'admin', to: 'users#admin', as: 'admin'

   get 'wszyscy', to: 'users#wszyscy', as: 'wszyscy'
 
   get 'dodaj', to: 'users#dodaj', as: 'dodaj'
 
   get 'usun', to: 'users#usun', as: 'usun'
 
   get 'kontrola', to: 'dissertations#kontrola', as: 'kontrola'
 
   get 'konf', to: 'users#konf', as: 'konf'
 
   get 'wyl', to: 'users#wyl', as: 'wyl'
 
   get '/moon', to: 'users#moon', as: 'moon'
 
   get '/sun', to: 'users#sun', as: 'sun'
=======
  #Admin

  get 'admin', to: 'users#admin', as: 'admin'

  get 'wszyscy', to: 'users#wszyscy', as: 'wszyscy'

  get 'dodaj', to: 'users#dodaj', as: 'dodaj'

  get 'usun', to: 'users#usun', as: 'usun'

  get 'kontrola', to: 'dissertations#kontrola', as: 'kontrola'

  get 'konf', to: 'users#konf', as: 'konf'

  get 'wyl', to: 'users#wyl', as: 'wyl'

  get '/moon', to: 'users#moon', as: 'moon'

  get '/sun', to: 'users#sun', as: 'sun'
>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :dissertations
    enum role: [:student, :promoter, :admin]
    def set_default_role
        self.role ||= :student
    end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :authenticate_admin!
  

    #Dodawanie nowego użytkownika do bazy danych jako ADMIN
    def new
      @new_user = User.new
    end
  
    def create
      @new_user = User.new(user_params)

        if params[:user][:is_student] == '1'
            @new_user.role = 0
        elsif params[:user][:is_promoter] == '1'
            @new_user.role = 1 
        elsif params[:user][:is_admin] == '1'
            @new_user.role = 2
        else 'Podałeś złe parametry'
        end

      if @new_user.save
        redirect_to dodaj_path, notice: 'Użytkownik został dodany pomyślnie.'
      else
        render :new
      end
    end

    #Usuwanie użytkowników z bazy danych jako ADMIN
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to usun_path, notice: 'Użytkownik został pomyślnie usunięty.'
    end
    
    private
  
    def user_params
      params.require(:user).permit(:index, :password, :is_student, :is_promoter, :is_admin, :email, :encrypted_password)
    end

    def authenticate_admin!
        redirect_to root_path, alert: 'Brak dostępu.' unless current_user && current_user.is_admin?
    end
  end
  

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, only: [:moon, :sun]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  def wszyscy 
    @users = User.all
  end

  def dodaj 
    @new_user = User.new
  end

  def usun 
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end
  
  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      if user.student? && user.email.end_with?('@student.pwr.edu.pl')
        # Logowanie dla studenta z domeną @student.pwr.edu.pl
        # Przeprowadź odpowiednie akcje
      elsif user.promoter? && user.email.end_with?('@pwr.edu.pl')
        # Logowanie dla promotora z domeną @pwr.edu.pl
        # Przeprowadź odpowiednie akcje
      elsif user.admin?
        # Logowanie dla admina - dowolna domena
        # Przeprowadź odpowiednie akcje
      else
        # Obsługa innych przypadków (np. błędne dane logowania)
      end
    else
      # Obsługa przypadku, gdy użytkownik nie istnieje lub podano błędne dane logowania
    end
  end

  

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "Użytkownik został pomyślnie usunięty." }
      format.json { head :no_content }
    end
  end

    #KONFIGURACJA STRONY - ADMIN - ZMIANA WYGLĄDU NA JASNY I CIEMNY

    def moon 
      cookies[:moon] = {
        value: 'dark mode on'
      }
      if @logged_in_user
        redirect_to konf_path
      else
        redirect_to admin_path
      end
    end
  
    def sun 
      cookies.delete(:moon)
      if @logged_in_user
        redirect_to konf_path
      else
        redirect_to admin_path
      end
    end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:index, :password, :is_student, :is_promoter, :is_admin, :email, :encrypted_password)
    end

    def authenticate_admin!
      redirect_to root_path, alert: 'Brak dostępu.' unless current_user && current_user.is_admin?
    end
    
  end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :index, style: "display: block" %>
    <%= form.number_field :index %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :is_student, style: "display: block" %>
    <%= form.check_box :is_student %>
  </div>

  <div>
    <%= form.label :is_promoter, style: "display: block" %>
    <%= form.check_box :is_promoter %>
  </div>

  <div>
    <%= form.label :is_admin, style: "display: block" %>
    <%= form.check_box :is_admin %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>Index:</strong>
    <%= user.index %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

  <p>
    <strong>Is student:</strong>
    <%= user.is_student %>
  </p>

  <p>
    <strong>Is promoter:</strong>
    <%= user.is_promoter %>
  </p>

  <p>
    <strong>Is admin:</strong>
    <%= user.is_admin %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/konf.html.erb
<%= stylesheet_link_tag('konf.css') %>
<div class="cont">
<div class="a">
<%= image_tag "logo2.png", height: 90 %>
</div>

<div class="b">
<ol>
<li><%= link_to "Home", "/admin", class:"index-link" %></li>
<li><span class="index-link">Zarządzanie użytkownikami</span>
  <ul>
    <li><%= link_to "Wszyscy użytkownicy", "/wszyscy", class:"index-link" %></li>
    <li><%= link_to "Dodaj użytkownika", "/dodaj", class:"index-link" %></li>
    <li><%= link_to "Usuń użytkownika", "/usun", class:"index-link" %></li>
  </ul>
</li>
<li><%= link_to "Kontrola prac", "/kontrola", class:"index-link" %></li>
<li><%= link_to "Konfiguracja", "/konf", class:"index-link" %></li>
<li><%= link_to "Wyloguj się", "/wyl", class:"index-link" %></li>
</ol>
</div>

<div class="main">
<h1>Zmień wygląd strony dla wszystkich użytkowników!</h1>

<% if cookies[:moon] %>
<%= button_to 'Tryb jasny', sun_path, method: :get, class: :przycisk%>
<% else %>
<%= button_to 'Tryb ciemny', moon_path, method: :get, class: :przycisk%>
<% end %>

</div>
</div>


<footer>
    <p>&copy; 2023 Obsługa Pracy Dyplomowej</p>
</footer>

app/views/users/pomoc.html.erb
<%= stylesheet_link_tag('pomoc.css') %>

<div class="cont">
<div class="a">
<%= image_tag "logo2.png", height: 90 %>
</div>

<div class="b">
<div id="bookmarksContainer">
<ol>
<li><%= link_to "Home", "/student", class:"bookmark", id: "bookmark7" %></li>
<li><span class="bookmark">Praca dyplomowa</span>
  <ul>
    <li><%= link_to "Harmonogram", "/harmonogram", class:"bookmark", id: "bookmark1" %></li>
    <li><%= link_to "Materiały", "/materialy", class:"bookmark", id: "bookmark2" %></li>
    <li><%= link_to "Instrukcja", "/instrukcja", class:"bookmark", id: "bookmark3" %></li>
    <li><%= link_to "Prześlij pracę", "/praca", class:"bookmark", id: "bookmark4" %></li>
  </ul>
</li>
<li><%= link_to "Pomoc", "/pomoc", class:"bookmark", id: "bookmark5" %></li>
<li><%= link_to "Wyloguj się", "/wyloguj",class:"bookmark", id: "bookmark6" %></li>
</ol>
</div>
</div>

<div class="c">
<form>
<input type="search" id="searchInput" placeholder="Szukaj na stronie...">
<button type="button" class="button" id="searchButton"><b> 🔎 </b></button>
</form>
</div>


<div class="e">
<h1> Pomoc </h1>
<p>Witaj w sekcji pomocy! Znajdziesz tutaj przydatne informacje i zasoby, które pomogą Ci w nawigacji po naszej stronie. </p>
<h2> FAQ: Najczęściej zadawane pytania </h2>

<div class="faqContainer">
<div class="faq-question" onclick="toggleFAQ('faq1')">W jakis sposób złożyć pracę dyplomową?<div class="aa">▼</div></div>
<div class="faq-answer" id="faq1">
    Aby załadować swoją pracę dyplomową na stronę, zaloguj się a następnie przejdź do sekcji "Praca dyplomowa" i postępuj zgodnie z instrukcjami na ekranie.
</div>
<div class="faq-question" onclick="toggleFAQ('faq2')">Gdzie znajdę harmonogram obron prac dyplomowych?<div class="aa">▼</div></div>
<div class="faq-answer" id="faq2">
    Harmonogram obron prac dyplomowych dostępny jest w sekcji "Harmonogram". Znajdziesz tam aktualne daty i informacje dotyczące obron.
</div>
<div class="faq-question" onclick="toggleFAQ('faq4')">Czy jest możliwość wysłania pracy dyplomowej po terminie?<div class="aa">▼</div></div>
<div class="faq-answer" id="faq4">
    W naszym systemie istnieje taka opcja, będzie się to jednak wiązało z obniżeniem oceny przez prowadzącego.

</div>
</div>
</div>

<div class="d">
<div class="contact-container">
<h1 class="kontakt">Kontakt</h1>
<p>W razie jakichkolwiek problemów skontaktuj się z nami.</p>

<div class="contact-info">
    <p><strong>Email:</strong> praca_dyplomowa@gmail.com</p>
    <p><strong>Telefon:</strong> +48 123 456 789</p>
    <p><strong>Adres:</strong> ul. Jana Pawła 32, 51-215 Wrocław</p>
</div>
</div>
</div>
</div>

<footer>
    <p>&copy; 2023 Obsługa Pracy Dyplomowej</p>
</footer>

<script>
    function toggleFAQ(faqId) {
        var faqAnswer = document.getElementById(faqId);
        if (faqAnswer.style.display === "block") {
            faqAnswer.style.display = "none";
        } else {
            faqAnswer.style.display = "block";
        }
    }

    function redirectToMatchingBookmark() {
 
    var searchText = document.getElementById('searchInput').value.toLowerCase();

    var bookmarks = document.querySelectorAll('.bookmark');

    for (var i = 0; i < bookmarks.length; i++) {
        var bookmark = bookmarks[i];
      
        var bookmarkText = bookmark.innerText.toLowerCase();

        if (bookmarkText.includes(searchText)) {
            // Przekieruj do pasującej zakładki
            window.location.href = bookmark.href;
            return;
        }
    }

    alert("Nie znaleziono pasującej zakładki");
}

document.getElementById('searchButton').addEventListener('click', function() {
    redirectToMatchingBookmark();
});

</script>

app/views/users/praca.html.erb
<%= stylesheet_link_tag('praca.css') %>
<div class="cont">
<div class="a">
<%= image_tag "logo2.png", height: 90 %>
</div>

<div class="b">
<div id="bookmarksContainer">
<ol>
<li><%= link_to "Home", "/student", class:"bookmark", id: "bookmark7" %></li>
<li><span class="bookmark">Praca dyplomowa</span>
  <ul>
    <li><%= link_to "Harmonogram", "/harmonogram", class:"bookmark", id: "bookmark1" %></li>
    <li><%= link_to "Materiały", "/materialy", class:"bookmark", id: "bookmark2" %></li>
    <li><%= link_to "Instrukcja", "/instrukcja", class:"bookmark", id: "bookmark3" %></li>
    <li><%= link_to "Prześlij pracę", "/praca", class:"bookmark", id: "bookmark4" %></li>
  </ul>
</li>
<li><%= link_to "Pomoc", "/pomoc", class:"bookmark", id: "bookmark5" %></li>
<li><%= link_to "Wyloguj się", "/wyloguj",class:"bookmark", id: "bookmark6" %></li>
</ol>
</div>
</div>

<div class="c">
<form>
<input type="search" id="searchInput" placeholder="Szukaj na stronie...">
<button type="button" class="przycisk" id="searchButton"><b> 🔎 </b></button>
</form>
</div>

<div class="m">
<div class="l">
<h2> Praca dyplomowa </h2>
<span class="text">Status przesłanego zadania</span>
</div>

<div class="p">
<h4>Aktualny czas
<p id="currentDateTime"></p></h4>
</div>

<table>
<tr class="dwa">
    <td class="t"> Numer indeksu </td>
<<<<<<< HEAD
    <td><%= current_user.index %></td>
</tr>
<tr>
<tr>
  <td class="t"> Numer indeksu promotora </td>
  <% if current_user.index < 210010 %>
      <td><%= current_user.index + 10000 %></td>
  <% else %>
    <<td><%= current_user.index + 9990 %></td>
  <% end %>
</tr>


</tr>
<tr>
    <td class="t">Status przesłanego zadania</td>
    <td>
    # NIE ROZUMIEM PRESENT?
    <% if @dissertations.present? %>
    <% @dissertations.each do |dissertation| %>
      <% if dissertation.pdf.attached? %>
        <p class="tex">Przesłano do oceny</p>
      <% else %>
        <p class="tex">Brak przesłanych plików</p>
      <% end %>
    <% end %>
  <% else %>
    <p class="tex">Brak danych</p>
  <% end %>
    </td>
=======
    <td><% current_user.index %></td>
</tr>
<tr>
    <td class="t">Status przesłanego zadania</td>
    <td><p>XD</p></td>
>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b
</tr>
<tr class="dwa">
    <td class="t">Stan oceniania</td>
    <td>Nieocenione/Ocenione</td>
</tr>
<tr>
    <td class="t">Weryfikacja</td>
    <td>Zaakceptowana/Odrzucona</td>
</tr>
<tr class="hd">
    <td class="t">Przesłane pliki</td>
    <td>
<<<<<<< HEAD
    <% @dissertations.each do |dissertation| %>
        <p>Nazwa pliku: <%= link_to dissertation.pdf.filename, dissertation.pdf %></p>
    <br>Data dodania: <%= dissertation.created_at %></br>
            <% end %>
=======
        <% @dissertations.each do |dissertation| %>
    <p>Nazwa pliku: <%= link_to dissertation.pdf.filename, dissertation.pdf %></p>
<br>Data dodania: <%= dissertation.created_at %></br>
        <% end %>
>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b
    </td>
</tr>
<tr class="h">
    <td class="t">Komentarz do przesłanej pracy</td>
    <td> </td>
</tr>
<tr class="hd">
    <td class="t">Recenzja</td>
    <td> </td>
</tr>
</table>
<center>
<<<<<<< HEAD
<%= form_with(model: @dissertation, url: dissertations_path, local: true, html: { multipart: true }) do |form| %>
    <%= form.fields_for :dissertation do |dissertation_form| %>
      <div>
        <%= dissertation_form.label :pdf, 'Wybierz plik PDF' %>
        <%= dissertation_form.file_field :pdf %>
      </div>
    <% end %>
  
    <div>
      <%= form.submit 'Dodaj pracę dyplomową' %>
    </div>
  <% end %>
  
=======
    <%= form_with(model: @dissertation, url: dissertations_path, local: true, html: { multipart: true }) do |form| %>
    <div>    
        <%= form.label :pdf, 'Wybierz plik PDF' %>
        <%= form.file_field :pdf %>
    </div>
    <div>
        <%= form.submit 'Dodaj pracę dyplomową' %>
    </div>
    <% end %>
>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b
<p class="praca">W każdej chwili możesz zmienić swoją pracę.</p>
</center>
</div>
</div>

<footer>
    <p>&copy; 2023 Obsługa Pracy Dyplomowej</p>
</footer>

<script>

function redirectToMatchingBookmark() {
 
var searchText = document.getElementById('searchInput').value.toLowerCase();

var bookmarks = document.querySelectorAll('.bookmark');

for (var i = 0; i < bookmarks.length; i++) {
    var bookmark = bookmarks[i];
  
    var bookmarkText = bookmark.innerText.toLowerCase();

    if (bookmarkText.includes(searchText)) {
        // Przekieruj do pasującej zakładki
        window.location.href = bookmark.href;
        return;
    }
}

alert("Nie znaleziono pasującej zakładki");
}

document.getElementById('searchButton').addEventListener('click', function() {
redirectToMatchingBookmark();
});


function updateDateTime() {
    var currentDate = new Date();
    var day = currentDate.toLocaleDateString();
    var time = currentDate.toLocaleTimeString();

    var dateTimeString = day + ' ' + time;
    document.getElementById('currentDateTime').innerHTML = dateTimeString;
  }

  setInterval(updateDateTime, 1000);

  window.onload = updateDateTime;
  </script>

app/views/users/prace.html.erb
<%= stylesheet_link_tag('praca.css') %>
<div class="cont">
<div class="a">
<%= image_tag "logo2.png", height: 90 %>
</div>
<div class="b">
<div id="bookmarksContainer">
<ol>
<li><%= link_to "Home", "/promoter", class:"bookmark", id: "bookmark1" %></li>
<li><%= link_to "Prace Dyplomowe", "/prace", class:"bookmark" , id: "bookmark4"%></li>
<li><%= link_to "Studenci", "/studenci", class:"bookmark", id: "bookmark2" %></li>
<li><%= link_to "Wyloguj", "/wyloguj", class:"bookmark" , id: "bookmark5"%></li>
</ol>
</div>
</div>

<div class="c">
<form>
<input type="search" id="searchInput" placeholder="Szukaj na stronie...">
<button type="button" class="button" id="searchButton"><b> 🔎 </b></button>
</form>
</div>
</div>

<div class="main">
<center><h1>Otrzymane prace od studentów</h1></center>
</div>


<div class="table">
    <table cellspacing="1" cellpadding="15" border="1" style="width: 100%;">
        <tbody>
        <tr class="tr">
            <td width="25%" valign="top">
                <center>Indeks studenta:</center>
            </td>
            <td width="25" valign="top">
                <center>student_index</center>
            </td>
        </tr>
        <tr class="tr">
            <td width="25%" valign="top">
            <center>Status przesłania Pracy Dyplomowej:</center>
            </td>
            <td width="25%" valign="top">
            <center>Nie próbowano/Przesłana</center>
            <% if @dissertations.present? %>
            <% @dissertations.each do |dissertation| %>
             <% if dissertation.pdf.attached? %>
            <p class="tex">Przesłano do oceny</p>
            <% else %>
            <p class="tex">Brak przesłanych plików</p>
             <% end %>
            <% end %>
             <% else %>
            <p class="tex">Brak danych</p>
            <% end %>
            </td>
        </tr>
        <tr class="tr">
            <td width="25%" valign="top">
            <center>Ostatnia modyfikacja:</center>
            </td>
            <td width="25%" valign="top">
            <center>Czas</center>
            </td>
        </tr> 
        <tr class="tr">
            <td width="25%" valign="top">
            <center>Praca Dyplomowa:</center>
            </td>
            <td width="25%" valign="top">
            <center>Załącznik</center>
            </td>
        </tr> 
        <tr class="tr">
            <td width="25%" valign="top">
            <center>Stan oceniania:</center>
            </td>
            
            <td width="25%" valign="top">
            <%= form_with dissertation: @dissertation do |form| %>
                <center>
                <input type="radio" id="zaakceptowana" name="fav_language" value="zaakceptowana">
                <label for="zaakceptowana">Zaakceptowana</label><br>
                <input type="radio" id="Niezaakceptowana" name="fav_language" value="Niezaakceptowana">
                <label for="Niezaakceptowana">Niezaakceptowana</label><br>
                </center>
            <tr class="tr">
            <td width="25%" valign="top">
            <center>Ocena:</center>
            </td>
            <td width="25%" valign="top">
            <center>
            <%= form.text_field :mark %>
                <%= form.submit 'Dodaj ocene'%>
                <% end %>
            </center>
            </td>
        </tr> 
        </tr>
        </tr>
        <tr class="tr">
            <td width="25%" valign="top">
            <center>Recenzja:</center>
            </td>
            <td width="25%" valign="top">
            <%= form_with(model: @dissertation, url: dissertations_path, local: true, html: { multipart: true }) do |form| %>
                <center> 
                <div>  
                 
                    <%= form.label :recenzja, 'Wybierz plik PDF' %>
                    <%= form.file_field :recenzja %>
                    
                </div>
                <div>
                    <%= form.submit 'Dodaj recenzje' %>
                </div>
                </center>
                <% end %>
            </td>
        </tr>
        <tr class="tr">
            <td width="25%" valign="top">
            <center>Komentarz:</center>
            </td>
            <td width="25%" valign="top">
            <%= form_with dissertation: @dissertation do |form| %>
                <center> 
                <%= form.text_field :feedback %>
                <%= form.submit 'Dodaj komentarz'%>
                </center> 
              <% end %>
            </td>
              
        </tbody>
    </table>
</div>

<div class="lewy">
<br> </br>
<br> </br>
</div>



<footer>
    <p>&copy; 2023 Obsługa Pracy Dyplomowej</p>
</footer>

<script>
function redirectToMatchingBookmark() {
 
    var searchText = document.getElementById('searchInput').value.toLowerCase();

    var bookmarks = document.querySelectorAll('.bookmark');

    for (var i = 0; i < bookmarks.length; i++) {
        var bookmark = bookmarks[i];
      
        var bookmarkText = bookmark.innerText.toLowerCase();

        if (bookmarkText.includes(searchText)) {
            // Przekieruj do pasującej zakładki
            window.location.href = bookmark.href;
            return;
        }
    }

    alert("Nie znaleziono pasującej zakładki");
}

document.getElementById('searchButton').addEventListener('click', function() {
    redirectToMatchingBookmark();
});
</script>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/users/usun.html.erb
<%= stylesheet_link_tag('usun.css') %>
<div class="cont">
<div class="a">
<%= image_tag "logo2.png", height: 90 %>
</div>

<div class="b">
<ol>
<li><%= link_to "Home", "/admin", class:"index-link" %></li>
<li><span class="index-link">Zarządzanie użytkownikami</span>
  <ul>
    <li><%= link_to "Wszyscy użytkownicy", "/wszyscy", class:"index-link" %></li>
    <li><%= link_to "Dodaj użytkownika", "/dodaj", class:"index-link" %></li>
    <li><%= link_to "Usuń użytkownika", "/usun", class:"index-link" %></li>
  </ul>
</li>
<li><%= link_to "Kontrola prac", "/kontrola", class:"index-link" %></li>
<li><%= link_to "Konfiguracja", "/konf", class:"index-link" %></li>
<li><%= link_to "Wyloguj się", "/wyl", class:"index-link" %></li>
</ol>
</div>

<div class="mai">
<h1>Usuń użytkownika</h1>

<% if flash[:notice] %>
    <p class="not"><%= flash[:notice] %></p>
    <% end %> 

<table>
  <thead>
    <tr>
      <th>Id Studenta</th>
      <th>Nazwa</th>
      <th>Indeks</th>
      <th>Rola</th>
      <th class="akcje">Akcje</th> 
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class="id"><%= user.id %></td>
        <td><%= user.index %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td class="akcje">
          <%= button_to 'Usuń', user, method: :delete, data: { confirm: 'Czy na pewno chcesz usunąć tego użytkownika?' }, class: "usun"%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
</div>

<footer>
    <p>&copy; 2023 Obsługa Pracy Dyplomowej</p>
</footer>