config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: 'sessions' }
  resources :dissertations, only: [:new, :create, :destroy]
  resources :users
  
  namespace :admin do
    resources :users, only: [:new, :create, :destroy]
  end
<<<<<<< HEAD
=======

>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b
  #Ogólna

  root 'static_pages#index'

  get 'welcome', to: 'static_pages#welcome', as: 'welcome'

  get 'index', to: 'static_pages#index', as: 'index'
  
  get 'authors', to: 'static_pages#authors', as: 'authors'

  get 'logowanie', to: 'static_pages#logowanie', as: 'logowanie'

  get 'help', to: 'static_pages#help', as: 'help'

  #Student

  get 'student', to: 'users#student', as: 'student'

  get 'materialy', to: 'users#materialy', as: 'materialy'

  get 'harmonogram', to: 'users#harmonogram', as: 'harmonogram'

  get 'instrukcja', to: 'users#instrukcja', as: 'instrukcja'

  get 'wyloguj', to: 'users#wyloguj', as: 'wyloguj'

  get 'praca', to: 'dissertations#new', as: 'praca'

  get 'pomoc', to: 'users#pomoc', as: 'pomoc'

<<<<<<< HEAD
  #Promoter

  get 'promoter', to: 'users#promoter', as: 'promoter'

  patch 'dissertations/:id', to: 'dissertations#edit', as: 'update_dissertation'
  
  get 'studenci', to: 'dissertations#studenci', as: 'studenci'

  get 'wylogowanie', to: 'users#wylogowanie', as: 'wylogowanie'

   #Admin

   get 'admin', to: 'users#admin', as: 'admin'

   get 'wszyscy', to: 'users#wszyscy', as: 'wszyscy'
 
   get 'dodaj', to: 'users#dodaj', as: 'dodaj'
 
   get 'usun', to: 'users#usun', as: 'usun'
 
   get 'kontrola', to: 'dissertations#kontrola', as: 'kontrola'
 
   get 'konf', to: 'users#konf', as: 'konf'
 
   get 'wyl', to: 'users#wyl', as: 'wyl'
 
   get '/moon', to: 'users#moon', as: 'moon'
 
   get '/sun', to: 'users#sun', as: 'sun'
=======
  #Admin

  get 'admin', to: 'users#admin', as: 'admin'

  get 'wszyscy', to: 'users#wszyscy', as: 'wszyscy'

  get 'dodaj', to: 'users#dodaj', as: 'dodaj'

  get 'usun', to: 'users#usun', as: 'usun'

  get 'kontrola', to: 'dissertations#kontrola', as: 'kontrola'

  get 'konf', to: 'users#konf', as: 'konf'

  get 'wyl', to: 'users#wyl', as: 'wyl'

  get '/moon', to: 'users#moon', as: 'moon'

  get '/sun', to: 'users#sun', as: 'sun'
>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b

end

app/models/dissertation.rb
class Dissertation < ApplicationRecord
  
    belongs_to :user
    has_one_attached :pdf
<<<<<<< HEAD
    has_one_attached :review_pdf
=======
>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b

    validates :pdf, presence: true
    validate :user_has_no_other_dissertation
    
    after_commit :check_pdf_attachment, on: [:create, :update]

<<<<<<< HEAD
    def update_attachments(params)
      pdf.attach(params[:pdf]) if params[:pdf].present?
      review_pdf.attach(params[:review_pdf]) if params[:review_pdf].present?
    end

    private
    validate :validate_pdf_format

    def validate_pdf_format
      if pdf.attached? && !pdf.blob.content_type.in?(%w(application/pdf))
        errors.add(:pdf, 'Musisz wybrać plik w formacie PDF.')
      end
      if review_pdf.attached? && !pdf.blob.content_type.in?(%w(application/pdf))
        errors.add(:review_pdf, 'Musisz wybrać plik w formacie PDF.')
      end
    end

      def user_has_no_other_dissertation
        if user&.dissertations&.where.not(id: id)&.exists?
          errors.add(:user, 'Użytkownik już dodał inną pracę dyplomową.')
        end
      end

=======
    private

    def validate_pdf_format
        if pdf.attached? && !pdf.blob.content_type.in?(%w(application/pdf))
          errors.add(:pdf, 'Musisz wybrać plik w formacie PDF.')
        end
      end

    def user_has_no_other_dissertation
        if user&.dissertations&.exists?
          errors.add(:user, 'Użytkownik już dodał pracę dyplomową.')
        end
    end

>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b
    def check_pdf_attachment
        # Sprawdź, czy PDF został załączony po zapisaniu rekordu
        if pdf.attached? && pdf.attachment
          Rails.logger.debug("PDF attached? true")
        else
          Rails.logger.debug("PDF attached? false")
        end
      end
<<<<<<< HEAD

      
=======
>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b
end

app/controllers/dissertations_controller.rb
class DissertationsController < ApplicationController
  before_action :set_dissertation, only: %i[ show edit update destroy ]
  before_action :authenticate_student!, only: [:create, :show, :check_submission_date_message, :set_submission_time_message]
<<<<<<< HEAD
  before_action :authenticate_promoter!, only: [:update, :show, :check_submission_date_message, :set_submission_time_message]
=======

>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b

  # GET /dissertations or /dissertations.json
  def index
    @dissertations = Dissertation.all
  end
  
  def kontrola
    @dissertations = Dissertation.all
  end

  def studenci
    @dissertations = Dissertation.all
  end
  
  def kontrola
    @dissertations = Dissertation.all
  end

  # GET /dissertations/1 or /dissertations/1.json

  def show
    @dissertation = Dissertation.find(params[:id])
  end
  
  def new
    @dissertations = current_user.dissertations || []
    @dissertation = Dissertation.new
    @submission_message = set_submission_time_message
  end
    

<<<<<<< HEAD
  def edit
    @dissertation = Dissertation.find(params[:id])
  end
    


=======

>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b
  #Dodawanie pracy dyplomowej przez użytkownika
  def create
    puts "Params: #{params.inspect}"
    
    promoters = User.where(is_promoter: true)

    if current_user.dissertations.exists?
      flash[:alert] = 'Dodałeś już swoją pracę dyplomową!'
      redirect_to praca_path
      return
    end

    @dissertation = current_user.dissertations.new(dissertation_params)
    @dissertation.index = current_user.dissertations.count + 1
    @dissertation.sending_date = Time.now
    @dissertation.student_index = current_user.index
<<<<<<< HEAD
    if current_user.index < 210010
      @dissertation.promoter_index = current_user.index + 10000
    else
      @dissertation.promoter_index = current_user.index + 9991
    end


    if @dissertation.save
      @dissertation.pdf.attach(params[:dissertation][:pdf]) # <- Zapis pliku w bazie
      redirect_to praca_path(@dissertation), notice: 'Praca dyplomowa została dodana pomyślnie.'
    else
      render :new
    end
  end

  def update
    @dissertation = Dissertation.find(params[:id])
    if @dissertation.update(dissertation_params)
      @dissertation.update_attachments(params[:dissertation])
      redirect_to edit_dissertation_path(@dissertation), notice: 'Komentarz został dodany pomyślnie.'
    else
      render :edit
    end
  end

  #Kontrola czy praca została oddana na czas
  def set_submission_time_message
    if current_user.dissertations.exists?
      submission_date = current_user.dissertations.last.sending_date
      if submission_date < Date.new(2024, 1, 28)
        submission_time = (Date.new(2024, 1, 28) - submission_date.to_date).to_i
        @submission_time_message = "Praca została oddana #{submission_time} dni przed 28 stycznia 2024 roku."
      else
        submission_time = (submission_date.to_date - Date.new(2024, 1, 28)).to_i
        @submission_time_message = "Praca została oddana #{submission_time} dni po 28 stycznia 2024 roku."
      end
    else
      @submission_time_message = "Nie masz jeszcze oddanej pracy."
    end
  end


=======
    @dissertation.promoter_index = promoters.pluck(:index).sample


    if @dissertation.save
      @dissertation.pdf.attach(params[:dissertation][:pdf])
      redirect_to praca_path(@dissertation), notice: 'Praca dyplomowa została dodana pomyślnie.'
    else
      render :new
    end
  end

  #Kontrola czy praca została oddana na czas
  def set_submission_time_message
    if current_user.dissertations.exists?
      submission_date = current_user.dissertations.last.sending_date
      if submission_date < Date.new(2024, 1, 5)
        submission_time = (Date.new(2024, 1, 5) - submission_date.to_date).to_i
        @submission_time_message = "Praca została oddana #{submission_time} dni przed 5 stycznia 2024 roku."
      else
        submission_time = (submission_date.to_date - Date.new(2024, 1, 5)).to_i
        @submission_time_message = "Praca została oddana #{submission_time} dni po 5 stycznia 2024 roku."
      end
    else
      @submission_time_message = "Nie masz jeszcze oddanej pracy."
    end
  end


>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dissertation
      @dissertation = Dissertation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def dissertation_params
<<<<<<< HEAD
      params.require(:dissertation).permit(:index, :student_index, :promoter_index, :sending_date, :verification_date, :feedback, :mark, :user_id, :pdf, :review_pdf)
=======
      params.require(:dissertation).permit(:index, :student_index, :promoter_index, :sending_date, :user_id, :pdf)
>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b
    end

    def authenticate_student!
      redirect_to root_path, alert: 'Brak dostępu.' unless current_user && current_user.is_student?
    end
<<<<<<< HEAD

    def authenticate_promoter!
      redirect_to root_path, alert: 'Brak dostępu.' unless current_user && current_user.is_promoter?
    end
=======
>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b
    
end

app/helpers/dissertations_helper.rb
module DissertationsHelper
end

app/views/dissertations/_dissertation.html.erb
<div id="<%= dom_id dissertation %>">
  <p>
    <strong>Index:</strong>
    <%= dissertation.index %>
  </p>

  <p>
    <strong>Student index:</strong>
    <%= dissertation.student_index %>
  </p>

  <p>
    <strong>Promoter index:</strong>
    <%= dissertation.promoter_index %>
  </p>

  <p>
    <strong>Sending date:</strong>
    <%= dissertation.sending_date %>
  </p>

  <p>
    <strong>Feedback:</strong>
    <%= dissertation.feedback %>
  </p>

  <p>
    <strong>Mark:</strong>
    <%= dissertation.mark %>
  </p>

  <p>
    <strong>Review:</strong>
    <%= dissertation.review %>
  </p>

</div>

app/views/dissertations/_form.html.erb
<%= form_with(model: dissertation) do |form| %>
  <% if dissertation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(dissertation.errors.count, "error") %> prohibited this dissertation from being saved:</h2>

      <ul>
        <% dissertation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :index, style: "display: block" %>
    <%= form.number_field :index %>
  </div>

  <div>
    <%= form.label :student_index, style: "display: block" %>
    <%= form.number_field :student_index %>
  </div>

  <div>
    <%= form.label :promoter_index, style: "display: block" %>
    <%= form.number_field :promoter_index %>
  </div>

  <div>
    <%= form.label :sending_date, style: "display: block" %>
    <%= form.datetime_field :sending_date %>
  </div>

  <div>
    <%= form.label :feedback, style: "display: block" %>
    <%= form.text_field :feedback %>
  </div>

  <div>
    <%= form.label :mark, style: "display: block" %>
    <%= form.number_field :mark %>
  </div>

  <div>
    <%= form.label :review, style: "display: block" %>
    <%= form.text_field :review %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/dissertations/edit.html.erb
<%= stylesheet_link_tag('pra.css') %>
<div class="cont">
<div class="a">
<%= image_tag "logo2.png", height: 90 %>
</div>
<div class="b">
<div id="bookmarksContainer">
<ol>
    <li><%= link_to "Home", "/promoter", class:"bookmark", id: "bookmark1" %></li>
    <li><%= link_to "Studenci", "/studenci", class:"bookmark", id: "bookmark2" %></li>
    <li><%= link_to "Wyloguj", "/wylogowanie", class:"bookmark" , id: "bookmark3"%></li>
</ol>
</div>
</div>

<div class="c">
<form>
<input type="search" id="searchInput" placeholder="Szukaj na stronie...">
<button type="button" class="button" id="searchButton"><b> 🔎 </b></button>
</form>
</div>
</div>

<div class="m">
<div class="l">
<h2> Otrzymana praca od studenta </h2>
</div>
<div class="p">
<h4>Aktualny czas
<p id="currentDateTime"></p></h4>
</div>
<table>
<tr class="dwa">
    <td class="t"><center> Indeks studenta: </center></td>
    <td><center><%= @dissertation.student_index %></center></td>
        </tr>
        <tr class="t">  
        <td class="t"><center>Status przesłania Pracy Dyplomowej:</center></td>
            <% if @dissertation.pdf.attached? %>
                <% if @dissertation.mark.present? %>
                <td class="tex"><center> Oceniona<center></td>
                <% else %>
                <td><center> Przesłano do oceny<center></td>
                <% end %>
          <% else %>
          <td><center>Brak przesłanych plików</center></td>
          <% end %>
        </tr>
        <tr class="dwa">
            <td class="t"><center>Ostatnia modyfikacja:</center></td>
            <td><center><%= @dissertation.sending_date %></center> </td>
        </tr> 
        <tr class="tr">
            <td class="t"><center>Praca Dyplomowa:</center></td>
                <% if @dissertation.pdf.attached? && @dissertation.pdf.present? %>
                    <td><center><%= link_to @dissertation.pdf.filename %></center></td>
                <% else %>
                    <td><center>Brak przesłanej pracy</center></td>
                <% end %>
        </tr> 
        <tr class="dwa">
        <td class="t"><center>Stan oceniania:</center></td>
        <td>
        <%= form_with(model: @dissertation, url: dissertation_path(@dissertation), method: :patch, multipart: true) do |form| %>
            <center>
                        <input type="radio" id="zaakceptowana" name="fav_language" value="zaakceptowana">
                        <label for="zaakceptowana">Zaakceptowana</label><br>
                        <input type="radio" id="Odrzucona" name="fav_language" value="Odrzucona">
                        <label for="Odrzucona">Odrzucona</label><br>
            </center>
        
        </td>
        <tr class="tr">
        <td class="t"><center>Ocena:</center></td>
        <td><center><%= form.number_field :mark, class: "pole"  %></center></td>
        </tr>
        <tr class="dwa">
        <td class="t"><center>Komentarz:</center></td>
        <td><center><%= form.text_field :feedback, class: "pole" %></center></td>
        </tr>
        <tr class="tr">
        <td class="t"><center>Recenzja:</center></td>
            <% if @dissertation.review_pdf.attached? && @dissertation.review_pdf.present? %>
            <td><center><%= link_to @dissertation.review_pdf.filename  %></center></td>
            <% else %>
                <td><center>Brak recenzji</center></td>
            <% end %>
        </tr>
        </tr>
        </tbody>
    </table>
    <center><%= form.file_field :review_pdf, class: :button %></center>
            <center><%= form.submit 'Dodaj recenzje', class: :przycisk %></center>
          <% end %>
</div>





<footer>
    <p>&copy; 2023 Obsługa Pracy Dyplomowej</p>
</footer>

<script>

function redirectToMatchingBookmark() {
 
var searchText = document.getElementById('searchInput').value.toLowerCase();

var bookmarks = document.querySelectorAll('.bookmark');

for (var i = 0; i < bookmarks.length; i++) {
    var bookmark = bookmarks[i];
  
    var bookmarkText = bookmark.innerText.toLowerCase();

    if (bookmarkText.includes(searchText)) {
        // Przekieruj do pasującej zakładki
        window.location.href = bookmark.href;
        return;
    }
}

alert("Nie znaleziono pasującej zakładki");
}

function updateDateTime() {
    var currentDate = new Date();
    var day = currentDate.toLocaleDateString();
    var time = currentDate.toLocaleTimeString();

    var dateTimeString = day + ' ' + time;
    document.getElementById('currentDateTime').innerHTML = dateTimeString;
  }

  setInterval(updateDateTime, 1000);

  window.onload = updateDateTime;


  var targetDate = new Date("January 5, 2024 00:00:00").getTime();

  var countdownInterval = setInterval(function() {
      var currentDate = new Date().getTime();
      var timeDifference = targetDate - currentDate;

      var days = Math.floor(timeDifference / (1000 * 60 * 60 * 24));
      var hours = Math.floor((timeDifference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      var minutes = Math.floor((timeDifference % (1000 * 60 * 60)) / (1000 * 60));
      var seconds = Math.floor((timeDifference % (1000 * 60)) / 1000);
      document.getElementById('countdown').innerHTML = days + "d " + hours + "h " + minutes + "m " + seconds + "s ";

      if (timeDifference < 0) {
          clearInterval(countdownInterval);
          document.getElementById('countdown').innerHTML = "Czas minął!";
      }
  }, 1000);
  

  </script>

app/views/dissertations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Dissertations</h1>

<div id="dissertations">
  <% @dissertations.each do |dissertation| %>
    <%= render dissertation %>
    <p>
      <%= link_to "Show this dissertation", dissertation %>
    </p>
  <% end %>
</div>

<%= link_to "New dissertation", new_dissertation_path %>

app/views/dissertations/new.html.erb
<%= stylesheet_link_tag('praca.css') %>
<div class="cont">
<div class="a">
<%= image_tag "logo2.png", height: 90 %>
</div>

<div class="b">
<div id="bookmarksContainer">
<ol>
<li><%= link_to "Home", "/student", class:"bookmark", id: "bookmark7" %></li>
<li><span class="bookmark">Praca dyplomowa</span>
  <ul>
    <li><%= link_to "Harmonogram", "/harmonogram", class:"bookmark", id: "bookmark1" %></li>
    <li><%= link_to "Materiały", "/materialy", class:"bookmark", id: "bookmark2" %></li>
    <li><%= link_to "Instrukcja", "/instrukcja", class:"bookmark", id: "bookmark3" %></li>
    <li><%= link_to "Prześlij pracę", "/praca", class:"bookmark", id: "bookmark4" %></li>
  </ul>
</li>
<li><%= link_to "Pomoc", "/pomoc", class:"bookmark", id: "bookmark5" %></li>
<li><%= link_to "Wyloguj się", "/wyloguj",class:"bookmark", id: "bookmark6" %></li>
</ol>
</div>
</div>

<div class="c">
<form>
<input type="search" id="searchInput" placeholder="Szukaj na stronie...">
<button type="button" class="przycisk" id="searchButton"><b> 🔎 </b></button>
</form>
</div>

<div class="m">
<div class="l">
<h2> Praca dyplomowa </h2>
<span class="text">Status przesłanego zadania</span>

<% if flash[:alert].present? %>
<div id="alert" class="alert">
  <%= flash[:alert] %>
</div>
<% end %>

</div>
<div class="p">
<h4>Aktualny czas
<p id="currentDateTime"></p></h4>
</div>
<table>
<tr class="dwa">
    <td class="t"> Numer indeksu </td>
    <td><%= current_user.index %></td>
</tr>
<tr>
    <td class="t">Status przesłanego zadania</td>
    <td>
    <% @dissertations.each do |dissertation| %>
<<<<<<< HEAD
      <% if dissertation.pdf.attached? %>
        <% if dissertation.mark.present? %>
          <p class="tex">Oceniona</p>
        <% else %>
          <p class="tex">Przesłano do oceny</p>
        <% end %>
      <% else %>
        <p class="tex">Nie przesłano do oceny</p>
      <% end %>
=======
    <% if dissertation.pdf.attached? %>
        <p class="tex">Przesłano do oceny</p>
    <% end %>
>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b
    <% end %>
    </td>
</tr>
<tr class="dwa">
    <td class="t">Stan oceniania</td>
<<<<<<< HEAD
    <td>
    <% @dissertations.each do |dissertation| %>
      <% if dissertation && dissertation.mark.present? %>
        <% if dissertation.mark > 2 %>
          <p class="tex">Twoja praca została ZAAKCEPTOWANA</p>
        <% else %>
          <p>Twoja praca została ODRZUCONA</p>
        <% end %>
      <% else %>
        <p>Twoja praca nie została oceniona</p>
      <% end %>
    <% end %>
    </td>
=======
    <td>Ocenione/Nieocenione</td>
>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b
</tr>
<tr>
    <td class="t">Weryfikacja</td>
    <td>
    <p><%= @submission_message %></p></td>
</tr>
<tr class="hd">
    <td class="t">Przesłane pliki</td>
    <td>
    <% @dissertations.each do |dissertation| %>
        <% if dissertation.pdf.attached? %>
            <%= link_to dissertation.pdf.blob.filename, rails_blob_path(dissertation.pdf, disposition: "attachment") %>
            <p>Data wysłania: <%= dissertation.sending_date %></p>
        <% else %>
          Nie wysłałeś jeszcze swojej pracy dyplomowej.
        <% end %>
<<<<<<< HEAD
        <% end %>
=======
      <% end %>
>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b
    </td>
</tr>
<tr class="h">
    <td class="t">Komentarz do przesłanej pracy</td>
<<<<<<< HEAD
      <td>
      <% @dissertations.each do |dissertation| %>
        <% if dissertation.feedback.present? %>
       <%= dissertation.feedback %>
       <p>Twoja ocena to: <%= dissertation.mark %></p>
        <% else %>
        Brak komentarza
        <% end %>
      <% end %>
      </td>
</tr>
<tr class="hd">
    <td class="t">Recenzja</td>
    <td>
    <% @dissertations.each do |dissertation| %>
      <% if dissertation.review_pdf.present? %>
      <%= link_to dissertation.review_pdf.filename, dissertation.review_pdf if dissertation.review_pdf.attached? %>
      <p>Data zamieszczenia recenzji: <%= dissertation.updated_at%></p>
      <% else %>
      Tutaj pojawi się recenzja twojego prowadzącego
      <% end %>
    <% end %>
    </td>
=======
    <td>Tutaj pojawi się tekst wprowadzony przez prowadzącego</td>
</tr>
<tr class="hd">
    <td class="t">Recenzja</td>
    <td>Tutaj pojawi się plik przesłany przez prowadzącego</td>
>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b
</tr>
</table>
<center>
<%= form_with(model: @dissertation, url: dissertations_path, local: true, multipart: true) do |form| %>
    <%= form.file_field :pdf, class: :button %><br>
    <%= form.submit 'Dodaj pracę dyplomową', class: :przycisk %>
<% end %>
</center>
</div>
</div>

<footer>
    <p>&copy; 2023 Obsługa Pracy Dyplomowej</p>
</footer>

<script>

function redirectToMatchingBookmark() {
 
var searchText = document.getElementById('searchInput').value.toLowerCase();

var bookmarks = document.querySelectorAll('.bookmark');

for (var i = 0; i < bookmarks.length; i++) {
    var bookmark = bookmarks[i];
  
    var bookmarkText = bookmark.innerText.toLowerCase();

    if (bookmarkText.includes(searchText)) {
        // Przekieruj do pasującej zakładki
        window.location.href = bookmark.href;
        return;
    }
}

alert("Nie znaleziono pasującej zakładki");
}

function updateDateTime() {
    var currentDate = new Date();
    var day = currentDate.toLocaleDateString();
    var time = currentDate.toLocaleTimeString();

    var dateTimeString = day + ' ' + time;
    document.getElementById('currentDateTime').innerHTML = dateTimeString;
  }

  setInterval(updateDateTime, 1000);

  window.onload = updateDateTime;


<<<<<<< HEAD
  var targetDate = new Date("January 28, 2024 00:00:00").getTime();
=======
  var targetDate = new Date("January 5, 2024 00:00:00").getTime();
>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b

  var countdownInterval = setInterval(function() {
      var currentDate = new Date().getTime();
      var timeDifference = targetDate - currentDate;

      var days = Math.floor(timeDifference / (1000 * 60 * 60 * 24));
      var hours = Math.floor((timeDifference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      var minutes = Math.floor((timeDifference % (1000 * 60 * 60)) / (1000 * 60));
      var seconds = Math.floor((timeDifference % (1000 * 60)) / 1000);
      document.getElementById('countdown').innerHTML = days + "d " + hours + "h " + minutes + "m " + seconds + "s ";

      if (timeDifference < 0) {
          clearInterval(countdownInterval);
          document.getElementById('countdown').innerHTML = "Czas minął!";
      }
  }, 1000);
  

<<<<<<< HEAD
  </script>
=======
  </script>
>>>>>>> 9d4a4227e0f5e8b35a63d9ae6cd5293ba455f68b

app/views/dissertations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @dissertation %>

<div>
  <%= link_to "Edit this dissertation", edit_dissertation_path(@dissertation) %> |
  <%= link_to "Back to dissertations", dissertations_path %>

  <%= button_to "Destroy this dissertation", @dissertation, method: :delete %>
</div>